name: Deploy Flask App
#Theres a feature to be able to run our code withing github: "Github Action"
on:
  push: #Trigger
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Flask tests
      run: |
        # Replace with your actual test command
        python -m unittest discover tests
